name: Check codebase state

on:
  workflow_call:

jobs:
  check-codebase:
    name: Check Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check codebase linting
        run: npm run lint:check

      - name: Check codebase formatting
        run: npm run lint:check

      - name: Run codebase tests
        run: npm run test

      - name: Package application
        run: npm run build
